#include "xmc_gpio.h"
#include "xmc_uart.h"

#define MICROPY_HW_BOARD_NAME "RELAXKIT_XMC4700"
#define MICROPY_HW_MCU_NAME   "XMC4700_F144x2048"

#define SERIAL_BAUDRATE 115200
#define SERIAL_BUFF_SIZE 64
#define SERIAL_UART XMC_UART0_CH0
#define SERIAL_TX_PIN P1_5
#define SERIAL_TX_PIN_AF (XMC_GPIO_MODE_t)((int32_t)XMC_GPIO_MODE_OUTPUT_PUSH_PULL | (int32_t)P1_5_AF_U0C0_DOUT0)
#define SERIAL_RX_PIN P1_4
#define SERIAL_RX_INPUT USIC0_C0_DX0_P1_4
#define SERIAL_RX_IRQN USIC0_0_IRQn
#define SERIAL_RX_IRQHandler USIC0_0_IRQHandler
