#ifndef XMC47_14_ATTR4_PINS_H
#define XMC47_14_ATTR4_PINS_H

#define P0_0_ATTR  (DIG_IN_OUT)
#define P0_1_ATTR  (DIG_IN_OUT)
#define P0_2_ATTR  (DIG_IN_OUT)
#define P0_3_ATTR  (DIG_IN_OUT)
#define P0_4_ATTR  (DIG_IN_OUT)
#define P0_5_ATTR  (DIG_IN_OUT)
#define P0_6_ATTR  (DIG_IN_OUT)
#define P0_7_ATTR  (DIG_IN_OUT)
#define P0_8_ATTR  (DIG_IN_OUT)
#define P0_9_ATTR  (DIG_IN_OUT)
#define P0_10_ATTR (DIG_IN_OUT)
#define P0_11_ATTR (DIG_IN_OUT)
#define P0_12_ATTR (DIG_IN_OUT)
#define P0_13_ATTR (DIG_IN_OUT)
#define P0_14_ATTR (DIG_IN_OUT)
#define P0_15_ATTR (DIG_IN_OUT)

#define P1_0_ATTR  (DIG_IN_OUT)
#define P1_1_ATTR  (DIG_IN_OUT)
#define P1_2_ATTR  (DIG_IN_OUT)
#define P1_3_ATTR  (DIG_IN_OUT)
#define P1_4_ATTR  (DIG_IN_OUT)
#define P1_5_ATTR  (DIG_IN_OUT)
#define P1_6_ATTR  (DIG_IN_OUT)
#define P1_7_ATTR  (DIG_IN_OUT)
#define P1_8_ATTR  (DIG_IN_OUT)
#define P1_9_ATTR  (DIG_IN_OUT)
#define P1_10_ATTR (DIG_IN_OUT)
#define P1_11_ATTR (DIG_IN_OUT)
#define P1_12_ATTR (DIG_IN_OUT)
#define P1_13_ATTR (DIG_IN_OUT)
#define P1_14_ATTR (DIG_IN_OUT)
#define P1_15_ATTR (DIG_IN_OUT)

#define P2_0_ATTR  (DIG_IN_OUT)
#define P2_1_ATTR  (DIG_IN_OUT)
#define P2_2_ATTR  (DIG_IN_OUT)
#define P2_3_ATTR  (DIG_IN_OUT)
#define P2_4_ATTR  (DIG_IN_OUT)
#define P2_5_ATTR  (DIG_IN_OUT)
#define P2_6_ATTR  (DIG_IN_OUT)
#define P2_7_ATTR  (DIG_IN_OUT)
#define P2_8_ATTR  (DIG_IN_OUT)
#define P2_9_ATTR  (DIG_IN_OUT)
#define P2_10_ATTR (DIG_IN_OUT)
#define P2_11_ATTR (DIG_IN_OUT)
#define P2_12_ATTR (DIG_IN_OUT)
#define P2_13_ATTR (DIG_IN_OUT)
#define P2_14_ATTR (DIG_IN_OUT)
#define P2_15_ATTR (DIG_IN_OUT)

#define P3_0_ATTR  (DIG_IN_OUT)
#define P3_1_ATTR  (DIG_IN_OUT)
#define P3_2_ATTR  (DIG_IN_OUT)
#define P3_3_ATTR  (DIG_IN_OUT)
#define P3_4_ATTR  (DIG_IN_OUT)
#define P3_5_ATTR  (DIG_IN_OUT)
#define P3_6_ATTR  (DIG_IN_OUT)
#define P3_7_ATTR  (DIG_IN_OUT)
#define P3_8_ATTR  (DIG_IN_OUT)
#define P3_9_ATTR  (DIG_IN_OUT)
#define P3_10_ATTR (DIG_IN_OUT)
#define P3_11_ATTR (DIG_IN_OUT)
#define P3_12_ATTR (DIG_IN_OUT)
#define P3_13_ATTR (DIG_IN_OUT)
#define P3_14_ATTR (DIG_IN_OUT)
#define P3_15_ATTR (DIG_IN_OUT)

#define P4_0_ATTR  (DIG_IN_OUT)
#define P4_1_ATTR  (DIG_IN_OUT)
#define P4_2_ATTR  (DIG_IN_OUT)
#define P4_3_ATTR  (DIG_IN_OUT)
#define P4_4_ATTR  (DIG_IN_OUT)
#define P4_5_ATTR  (DIG_IN_OUT)
#define P4_6_ATTR  (DIG_IN_OUT)
#define P4_7_ATTR  (DIG_IN_OUT)

#define P5_0_ATTR  (DIG_IN_OUT)
#define P5_1_ATTR  (DIG_IN_OUT)
#define P5_2_ATTR  (DIG_IN_OUT)
#define P5_3_ATTR  (DIG_IN_OUT)
#define P5_4_ATTR  (DIG_IN_OUT)
#define P5_5_ATTR  (DIG_IN_OUT)
#define P5_6_ATTR  (DIG_IN_OUT)
#define P5_7_ATTR  (DIG_IN_OUT)
#define P5_8_ATTR  (DIG_IN_OUT)
#define P5_9_ATTR  (DIG_IN_OUT)
#define P5_10_ATTR (DIG_IN_OUT)
#define P5_11_ATTR (DIG_IN_OUT)

#define P6_0_ATTR  (DIG_IN_OUT)
#define P6_1_ATTR  (DIG_IN_OUT)
#define P6_2_ATTR  (DIG_IN_OUT)
#define P6_3_ATTR  (DIG_IN_OUT)
#define P6_4_ATTR  (DIG_IN_OUT)
#define P6_5_ATTR  (DIG_IN_OUT)
#define P6_6_ATTR  (DIG_IN_OUT)

#define P14_0_ATTR  (AN | DIG_IN)
#define P14_1_ATTR  (AN | DIG_IN)
#define P14_2_ATTR  (AN | DIG_IN)
#define P14_3_ATTR  (AN | DIG_IN)
#define P14_4_ATTR  (AN | DIG_IN)
#define P14_5_ATTR  (AN | DIG_IN)
#define P14_6_ATTR  (AN | DIG_IN)
#define P14_7_ATTR  (AN | DIG_IN)
#define P14_8_ATTR  (AN | DAC_OUT | DIG_IN)
#define P14_9_ATTR  (AN | DAC_OUT | DIG_IN)
#define P14_12_ATTR (AN | DIG_IN)
#define P14_13_ATTR (AN | DIG_IN)
#define P14_14_ATTR (AN | DIG_IN)
#define P14_15_ATTR (AN | DIG_IN)

#define P15_0_ATTR  (AN | DIG_IN)
#define P15_1_ATTR  (AN | DIG_IN)
#define P15_2_ATTR  (AN | DIG_IN)
#define P15_3_ATTR  (AN | DIG_IN)
#define P15_4_ATTR  (AN | DIG_IN)
#define P15_5_ATTR  (AN | DIG_IN)
#define P15_6_ATTR  (AN | DIG_IN)
#define P15_7_ATTR  (AN | DIG_IN)
#define P15_8_ATTR  (AN | DIG_IN)
#define P15_9_ATTR  (AN | DIG_IN)
#define P15_12_ATTR (AN | DIG_IN)
#define P15_13_ATTR (AN | DIG_IN)
#define P15_14_ATTR (AN | DIG_IN)
#define P15_15_ATTR (AN | DIG_IN)

#endif